name: bs_limit_browser
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  flutter_slidable: ^3.1.0
  dotted_border: ^2.1.0
  intl: ^0.19.0
  path_provider: ^2.1.3
  json_annotation: ^4.9.0
  drift: ^2.19.1
  drift_flutter: ^0.1.0
  copy_with_extension: ^5.0.4
  copy_with_extension_gen: ^5.0.4
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  go_router_builder: ^2.7.0
  json_serializable: ^6.8.0
  drift_dev: ^2.19.0

dependency_overrides:
  meta: ^1.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
